### ISSUE TITLE
tensorflow.py的命名要换一下，否则会报错"module 'tensorflow' has no attribute 'Variable'"

### ISSUE THREAD

**Issue by polegithub** [jindongwang/Deep-learning-activity-recognition#5]
tensorflow.py的命名要换一下,  不能使用"tensorflow", 否则会找不到真正的tensorflow package。
导致各种报错.

Traceback (most recent call last):
  File "/Downloads/Deep-learning-activity-recognition-master/tensorflow.py", line 199, in <module>
    network(X_train, Y_train, X_test, Y_test)
  File "/Downloads/Deep-learning-activity-recognition-master/tensorflow.py", line 154, in network
    config = Config(X_train, Y_train)
  File "/Downloads/Deep-learning-activity-recognition-master/tensorflow.py", line 102, in __init__
    'wc1': tf.Variable(tf.random_normal([1, self.kernel_size, self.n_channel, self.depth])),
AttributeError: module 'tensorflow' has no attribute 'Variable'

**Comment by jindongwang** [comment]
已改正
