### ISSUE TITLE
RuntimeError: The size of tensor a (128) must match the size of tensor b (9) at non-singleton dimension 0

### ISSUE THREAD

**Issue by tcxia** [jindongwang/Deep-learning-activity-recognition#8]
Traceback (most recent call last):
  File "main_pytorch.py", line 90, in <module>
    train(model, optimizer, train_loader, test_loader)
  File "main_pytorch.py", line 33, in train
    for index, (sample, target) in enumerate(train_loader):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 560, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 560, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/root/tcxia/Deep-learning-activity-recognition/pytorch/data_preprocess.py", line 93, in __getitem__
    return self.T(sample), target
  File "/usr/local/lib/python3.5/dist-packages/torchvision/transforms/transforms.py", line 61, in __call__
    img = t(img)
  File "/usr/local/lib/python3.5/dist-packages/torchvision/transforms/transforms.py", line 164, in __call__
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "/usr/local/lib/python3.5/dist-packages/torchvision/transforms/functional.py", line 208, in normalize
    tensor.sub_(mean[:, None, None]).div_(std[:, None, None])

**Comment by artur-ba** [comment]
I have the same issue. I am using Python **3.7** and Pytorch **1.1.0**

**Comment by tcxia** [comment]
> I have the same issue. I am using Python **3.7** and Pytorch **1.1.0**

Maybe you change the pytorch version to 0.4.0，it works!

**Comment by artur-ba** [comment]
I change python version to 3.6 and used Pytorch 0.4.0 but with the same result. Still error.
Only way to make it works for me is to remove:
`transforms.Normalize(mean=(0,0,0,0,0,0,0,0,0), std=(1,1,1,1,1,1,1,1,1))` from `pytorch/data_preprocess.py` line 105, but I don't know if this is a good solution. I will try to run this code with Python 3.5

**Comment by artur-ba** [comment]
Ok, I downgraded Python to 3.5 , Pytorch to 0.4.0 and Torchvision to 0.2.1 and it works. It would be nice if this project had `requirements.txt` with list of packages with specified versions or to be migrated to newest Pytorch

**Comment by jindongwang** [comment]
I update the code
